/**
 * ENVIRONMENT.md and project documentation generation.
 *
 * Pure functions with no DI dependencies, called by DevopsAgent step methods.
 */

import { InterviewResult } from '../interviewer/interview-result.interface';

// ─── ENVIRONMENT.md ──────────────────────────────────────────

/** Build the full ENVIRONMENT.md content from interview data */
export function buildEnvironmentDoc(
  projectName: string,
  interviewResult: InterviewResult,
): string {
  const ts = interviewResult.techStack ?? {};
  const deploy = interviewResult.deployment;
  const setup = interviewResult.setupInstructions;

  const sections: (string | null)[] = [
    `# Environment — ${projectName}`,
    `> Auto-generated by VibCode Hub DevOps Agent. Last updated: ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Project Overview',
    interviewResult.description || projectName,
    '',
    '## Tech Stack',
    ts.framework ? `- **Framework:** ${ts.framework}` : null,
    ts.language ? `- **Language:** ${ts.language}` : null,
    ts.backend && ts.backend !== 'none'
      ? `- **Backend:** ${ts.backend}`
      : null,
    ts.database && ts.database !== 'none'
      ? `- **Database:** ${ts.database}`
      : null,
    ...(ts.additional ?? []).map((a) => `- **Package:** ${a}`),
    '',
    '## Setup Commands',
    setup?.initCommand ? `- **Init:** \`${setup.initCommand}\`` : null,
    ...(setup?.additionalCommands ?? []).map(
      (cmd) => `- **Additional:** \`${cmd}\``,
    ),
    '',
    '## Development Server',
    deploy?.devServerCommand
      ? `- **Command:** \`${deploy.devServerCommand}\``
      : '- _Not configured_',
    deploy?.devServerPort ? `- **Port:** ${deploy.devServerPort}` : null,
    deploy?.buildCommand ? `- **Build:** \`${deploy.buildCommand}\`` : null,
    deploy?.isWebProject !== undefined
      ? `- **Web Project:** ${deploy.isWebProject ? 'Yes' : 'No'}`
      : null,
    '',
    '## MCP Servers',
    ...(interviewResult.mcpServers && interviewResult.mcpServers.length > 0
      ? interviewResult.mcpServers.map(
          (s) => `- **${s.name}** — ${s.purpose}`,
        )
      : ['- _None configured_']),
    '',
    '## Installed Packages',
    '_Updated automatically when packages are installed via the Infrastructure Chat._',
    '',
    '## Infrastructure Notes',
    '_Add notes about server configuration, environment variables, external services, etc._',
    '',
  ];

  return sections.filter((l): l is string => l !== null).join('\n');
}

// ─── PROJECT_KNOWLEDGE.md ────────────────────────────────────

/** Build the PROJECT_KNOWLEDGE.md content */
export function buildKnowledgeBaseDoc(
  projectName: string,
  interviewResult: InterviewResult,
): string {
  const ts = interviewResult.techStack ?? {};

  return [
    `# Project Knowledge Base — ${projectName}`,
    `> Auto-maintained by VibCode Hub. Updated: ${new Date().toISOString().split('T')[0]}`,
    '',
    '## Project Description',
    interviewResult.description || projectName,
    '',
    '## Tech Stack',
    ts.framework ? `- **Framework:** ${ts.framework}` : null,
    ts.language ? `- **Language:** ${ts.language}` : null,
    ts.backend ? `- **Backend:** ${ts.backend}` : null,
    ts.database ? `- **Database:** ${ts.database}` : null,
    ...(ts.additional ?? []).map((a) => `- ${a}`),
    '',
    '## Implemented Features',
    '_No features implemented yet. This section is updated automatically after each completed issue._',
    '',
    '## Architecture & Patterns',
    '_Will be populated after the Architect agent designs the project structure._',
    '',
    '## Key Files',
    '_Will be populated as code is added._',
    '',
    '## Known Constraints',
    '_None yet._',
    '',
  ]
    .filter((l) => l !== null)
    .join('\n');
}

// ─── README.md ───────────────────────────────────────────────

/** Build the README.md content */
export function buildReadme(
  projectName: string,
  interviewResult: InterviewResult,
): string {
  const ts = interviewResult.techStack ?? {};
  const deploy = interviewResult.deployment;
  const setup = interviewResult.setupInstructions;
  const features = (interviewResult.features ?? []).map((f, i) => {
    if (typeof f === 'string') return `${i + 1}. ${f}`;
    return `${i + 1}. **${f.title}** (${f.priority})${f.description ? ` — ${f.description}` : ''}`;
  });
  const techLine = [ts.framework, ts.language, ts.backend, ts.database]
    .filter(Boolean)
    .join(', ');

  return [
    `# ${projectName}`,
    '',
    interviewResult.description || `A ${techLine} project.`,
    '',
    '## Tech Stack',
    '',
    techLine ? `- ${techLine}` : '- See PROJECT_KNOWLEDGE.md for details',
    '',
    '## Features',
    '',
    features.length > 0 ? features.join('\n') : '- Coming soon',
    '',
    '## Getting Started',
    '',
    '### Prerequisites',
    '',
    ['java', 'spring', 'vaadin', 'quarkus'].some((k) =>
      (ts.framework ?? '').toLowerCase().includes(k),
    ) || (ts.language ?? '').toLowerCase().includes('java')
      ? '- JDK >= 17\n- Maven >= 3.9'
      : ts.language === 'TypeScript' || ts.framework
        ? '- Node.js >= 18'
        : '- See project documentation',
    (ts.framework ?? '').toLowerCase().includes('angular')
      ? '- Angular CLI (`npm install -g @angular/cli`)'
      : null,
    '',
    '### Installation',
    '',
    '```bash',
    `git clone <repository-url>`,
    `cd ${projectName.toLowerCase().replace(/\s+/g, '-')}`,
    setup?.initCommand ? setup.initCommand : 'npm install',
    '```',
    '',
    deploy?.devServerCommand
      ? [
          '### Development',
          '',
          '```bash',
          deploy.devServerCommand,
          '```',
          '',
          deploy.devServerPort
            ? `The dev server runs on http://localhost:${deploy.devServerPort}`
            : null,
          '',
        ]
          .filter(Boolean)
          .join('\n')
      : null,
    deploy?.buildCommand
      ? ['### Build', '', '```bash', deploy.buildCommand, '```', ''].join('\n')
      : null,
    '## License',
    '',
    'MIT',
    '',
  ]
    .filter((l) => l !== null)
    .join('\n');
}

// ─── CHANGELOG.md ────────────────────────────────────────────

/** Build initial CHANGELOG.md content */
export function buildChangelog(): string {
  return [
    '# Changelog',
    '',
    'All notable changes to this project will be documented in this file.',
    'This file is auto-maintained by VibCode Hub after each completed issue.',
    '',
    '## [Unreleased]',
    '',
    '### Added',
    '- Initial project setup',
    '',
  ].join('\n');
}

// ─── CONTRIBUTING.md ─────────────────────────────────────────

/** Build CONTRIBUTING.md content */
export function buildContributing(
  projectName: string,
  interviewResult: InterviewResult,
): string {
  const ts = interviewResult.techStack ?? {};

  return [
    `# Contributing to ${projectName}`,
    '',
    '## Development Workflow',
    '',
    'This project uses [VibCode Hub](https://hub.example.com) for AI-assisted development.',
    'Issues are automatically processed through a multi-agent pipeline:',
    '',
    '1. **Coder** — Implements the feature/fix',
    '2. **Code Reviewer** — Reviews code quality and patterns',
    '3. **Functional Tester** — Verifies acceptance criteria',
    '4. **UI Tester** — Checks UI/UX (for web projects)',
    '5. **Pen Tester** — Security analysis',
    '6. **Documenter** — Updates documentation',
    '',
    '## Branch Strategy',
    '',
    '- `main` — Production-ready code',
    '- `feature/<issue-id>-<title>` — Feature branches (auto-created)',
    '',
    '## Code Style',
    '',
    ts.language === 'TypeScript'
      ? [
          '- TypeScript strict mode',
          '- ESLint + Prettier for formatting',
          '- Meaningful variable and function names',
        ].join('\n- ')
      : '- Follow existing code conventions',
    '',
    '## Commit Messages',
    '',
    'We use [Conventional Commits](https://www.conventionalcommits.org/):',
    '- `feat:` — New feature',
    '- `fix:` — Bug fix',
    '- `docs:` — Documentation changes',
    '- `refactor:` — Code refactoring',
    '- `test:` — Test additions/changes',
    '',
  ].join('\n');
}

// ─── Wiki Scaffolding ────────────────────────────────────────

/** Build the wiki home page content */
export function buildWikiHome(
  projectName: string,
  interviewResult: InterviewResult,
): string {
  const ts = interviewResult.techStack ?? {};
  const techLine = [ts.framework, ts.language, ts.backend, ts.database]
    .filter(Boolean)
    .join(', ');
  const features = (interviewResult.features ?? []).map((f, i) => {
    if (typeof f === 'string') return `${i + 1}. ${f}`;
    return `${i + 1}. **${f.title}** (${f.priority})${f.description ? ` — ${f.description}` : ''}`;
  });

  return [
    `# ${projectName}`,
    '',
    interviewResult.description || `A ${techLine} project.`,
    '',
    '## Quick Links',
    '',
    '- [Environment](ENVIRONMENT) — Tech stack, dependencies, ports',
    '- [Project Knowledge](PROJECT_KNOWLEDGE) — Accumulated project knowledge',
    '- [Architecture](Architecture/Overview) — System architecture',
    '- [Changelog](CHANGELOG) — Version history',
    '',
    '## Features',
    '',
    features.length > 0
      ? features.join('\n')
      : '_No features implemented yet._',
    '',
    '---',
    `_Auto-generated by VibCode Hub — ${new Date().toISOString().split('T')[0]}_`,
  ].join('\n');
}

/** Build the wiki sidebar content */
export function buildWikiSidebar(projectName: string): string {
  return [
    `**${projectName}**`,
    '',
    '- [Home](home)',
    '- [Environment](ENVIRONMENT)',
    '- [Project Knowledge](PROJECT_KNOWLEDGE)',
    '- [Architecture](Architecture/Overview)',
    '- [Changelog](CHANGELOG)',
    '',
    '**Features**',
    '',
    '_Updated automatically after each completed issue._',
  ].join('\n');
}

/** Build the wiki architecture overview page */
export function buildWikiArchOverview(
  projectName: string,
  interviewResult: InterviewResult,
): string {
  const ts = interviewResult.techStack ?? {};
  const techLine = [ts.framework, ts.language, ts.backend, ts.database]
    .filter(Boolean)
    .join(', ');

  return [
    `# Architecture — ${projectName}`,
    '',
    '## Tech Stack',
    '',
    techLine ? `- ${techLine}` : '- See ENVIRONMENT page for details',
    '',
    '## System Overview',
    '',
    '_Will be populated after the Architect agent designs the project structure._',
    '',
    '## Data Model',
    '',
    '_Will be updated as the schema evolves._',
    '',
  ].join('\n');
}
